version: '3'

services:
  alumnus-api:
    build: .
    container-name: alumnus-api
    volumes: 
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - alumnus-db
    networks:
      - alumnus-network
  alumnus-db:
    image: postgres
    container-name: alumnus-db
    environment: 
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRES_PASSWORD: 'docker'
  volumes:
    - alumnus-db-data:/data
  networks:
    - alumnus-network
volumes:
  alumnus-db-data:
networks:
  alumnus-network:
    driver: bridge